const PHOTOS = [
  { url: "https://drive.google.com/uc?export=view&id=18kwuKcywAgHo7vF-DllLVgDnPa48bgN3", caption: "Juntos en el ShotMe 📸" },
  { url: "https://drive.google.com/uc?export=view&id=1h7N8QjiwbLW0JLZSI8By_wdpCVOWyK0i", caption: "Mi cumpleaños 🎂" },
  { url: "https://drive.google.com/uc?export=view&id=1nJcdyVAipnHSWHdMhz5mNjI9hVbW0a3f", caption: "Parque del Retiro 🌿" },
  { url: "https://drive.google.com/uc?export=view&id=1Hud0bnfJhp0ObYkI4O2AcoYDqvFYlHcp", caption: "Tu foto fav 🤍" },
  { url: "https://drive.google.com/uc?export=view&id=1meqDpqDqZ24gIgJAp7AKPoPUnG2U1wVR", caption: "Visca Barça 🔵🔴" },
  { url: "https://drive.google.com/uc?export=view&id=1YMIZIxawkhG2Bjw3IRJuLeqTqd1A_6rs", caption: "Muchos chupitos 🥃" },
  { url: "https://drive.google.com/uc?export=view&id=1OBj_A83iM5MsE75hm8X7BMsJdPHG8B5A", caption: "Primer evento familiar 👨‍👩‍👧" },
  { url: "https://drive.google.com/uc?export=view&id=1gNu2O641BnAPPlclnOPoNl7IOP94CrHn", caption: "Primer beso 💋" },
  { url: "https://drive.google.com/uc?export=view&id=1u_iKEB7iQk0ThdofSIZqIO36Xc1R3s0p", caption: "Visca Barça x2 🔵🔴" },
  { url: "https://drive.google.com/uc?export=view&id=1nr3mfXyR5YLVkjoK8FTtkbg8vOyphWRd", caption: "Viendo movies 🎬" },
  { url: "https://drive.google.com/uc?export=view&id=1RlfKOW4c7KWqvT0f_n2HtPN7YWH2QUgC", caption: "Bebés 👶🏻" },
  { url: "https://drive.google.com/uc?export=view&id=1NL589Eec_thSg5LHvTJVjtD9WOFJmTGs", caption: "Disfraces matching 🎃" },
  { url: "https://drive.google.com/uc?export=view&id=1t0SeA_K3O1mJVga9bgH3E6O9cN1qc7ZW", caption: "Mucho frío ❄️" },
  { url: "https://drive.google.com/uc?export=view&id=1MYMWXudSwllKdQWZHYl97Sqs32RSBRJL", caption: "Viendo Interstellar 🚀" },
  { url: "https://drive.google.com/uc?export=view&id=1z3jx0Lug_QhOG5Derfo9eJWMfE3FX7sl", caption: "Arco del Triunfo 🇫🇷" },
  { url: "https://drive.google.com/uc?export=view&id=1S-lu3buRmaF0TkFfS5sfXhrANnRrFFuf", caption: "Fontana di Trevi 🇮🇹" },
  { url: "https://drive.google.com/uc?export=view&id=1kaKqO42uSe56EnT8iFmgEsl77VrsVwqd", caption: "En la playita 🌊" },
  { url: "https://drive.google.com/uc?export=view&id=1K1rDLpBXc-7mnnK-aIxQFgpg5Su5N9nO", caption: "En la playita de nuevo 🌴" },
  { url: "https://drive.google.com/uc?export=view&id=1-5cllmFrJy20nr23-4RCgdnvIJBkuGiA", caption: "Mucha playita ☀️" },
  { url: "https://drive.google.com/uc?export=view&id=18qj42pB4HlvGQKcHSVdR2BjHrViaMouP", caption: "Sagrada Familia 🕌" },
  { url: "https://drive.google.com/uc?export=view&id=18jL1lDiGYzMXpfvGDgCE7_8s9GiJbkTW", caption: "Cuidando a nuestras mamis 🥰" },
  { url: "https://drive.google.com/uc?export=view&id=1rAku7FW2pPiJ7cFBqbc5vB7RjMb5Wwjc", caption: "Manejando 🚗" },
  { url: "https://drive.google.com/uc?export=view&id=1-btcoIol0xyQXcnLP8yz8Y2PMZ1NTDB9", caption: "Cena de navidad con amigos 🎄" },
  { url: "https://drive.google.com/uc?export=view&id=1xcJN7bGbS7rkvs8mAAFIemumYzZM7vlf", caption: "Mumiendo 😴" },
  { url: "https://drive.google.com/uc?export=view&id=12dNszc0aq08BGfgz2zh7VQyxg8yQmYqi", caption: "Parque de diversiones 🎡" },
  { url: "https://drive.google.com/uc?export=view&id=1CiXf_-WkFIpCDkqGXB2nBrx-xHCMb8rw", caption: "Con solsito en la cara 🌞" },
  { url: "https://drive.google.com/uc?export=view&id=1rdzsLw6E-sLh5xMAo0oIsgzQ7gwIgDYG", caption: "Hermosa foto 😍" },
  { url: "https://drive.google.com/uc?export=view&id=1EEHYSy6OWn8H5dC6VXiI8LSTKMF04S86", caption: "De paseo 🚶‍♀️" },
  { url: "https://drive.google.com/uc?export=view&id=1fsZImDmf5jcfziKHAvaZG2puxUMD3dhC", caption: "Despedida juntos 🤍" },
];
