const PHOTOS = [
  { url: "fotos/Foto 1.jpeg", caption: "Juntos en el ShotMe 📸" },
  { url: "fotos/Foto 2.jpeg", caption: "Mi cumpleaños 🎂" },
  { url: "fotos/Foto 3.jpeg", caption: "Parque del Retiro 🌿" },
  { url: "fotos/Foto 4.jpeg", caption: "Tu foto fav 🤍" },
  { url: "fotos/Foto 5.jpeg", caption: "Visca Barça 🔵🔴" },
  { url: "fotos/Foto 6.jpeg", caption: "Muchos chupitos 🥃" },
  { url: "fotos/Foto 7.jpeg", caption: "Primer evento familiar 👨‍👩‍👧" },
  { url: "fotos/Foto 8.jpeg", caption: "Primer beso 💋" },
  { url: "fotos/Foto 9.jpeg", caption: "Visca Barça x2 🔵🔴" },
  { url: "fotos/Foto 10.jpeg", caption: "Viendo movies 🎬" },
  { url: "fotos/Foto 11.jpeg", caption: "Bebés 👶🏻" },
  { url: "fotos/Foto 12.jpeg", caption: "Disfraces matching 🎃" },
  { url: "fotos/Foto 13.jpeg", caption: "Mucho frío ❄️" },
  { url: "fotos/Foto 14.jpeg", caption: "Viendo Interstellar 🚀" },
  { url: "fotos/Foto 15.jpeg", caption: "Arco del Triunfo 🇫🇷" },
  { url: "fotos/Foto 16.jpeg", caption: "Fontana di Trevi 🇮🇹" },
  { url: "fotos/Foto 17.jpeg", caption: "En la playita 🌊" },
  { url: "fotos/Foto 18.jpeg", caption: "En la playita de nuevo 🌴" },
  { url: "fotos/Foto 19.jpeg", caption: "Mucha playita ☀️" },
  { url: "fotos/Foto 20.jpeg", caption: "Sagrada Familia 🕌" },
  { url: "fotos/Foto 21.jpeg", caption: "Cuidando a nuestras mamis 🥰" },
  { url: "fotos/Foto 22.jpeg", caption: "Manejando 🚗" },
  { url: "fotos/Foto 23.jpeg", caption: "Cena de navidad con amigos 🎄" },
  { url: "fotos/Foto 24.jpeg", caption: "Mumiendo 😴" },
  { url: "fotos/Foto 25.jpeg", caption: "Parque de diversiones 🎡" },
  { url: "fotos/Foto 26.jpeg", caption: "Con solsito en la cara 🌞" },
  { url: "fotos/Foto 27.jpeg", caption: "Hermosa foto 😍" },
  { url: "fotos/Foto 28.jpeg", caption: "De paseo 🚶‍♀️" },
  { url: "fotos/Foto 29.jpeg", caption: "Despedida juntos 🤍" },
];
